import Head from 'next/head';
import React, { RefObject, useEffect, useRef, useState } from 'react';
import { HomeSection } from '../components/sections/HomeSection';
import Navbar from '../components/Navbar';
import { ProjectSection } from '../components/sections/ProjectSection';
import { AboutSection } from '../components/sections/AboutSection';
import { ContactSection } from '../components/sections/ContactSection';
import { Footer } from '../components/Footer';

export default function Home() {
  const [refs, setRefs] = useState<RefObject<HTMLDivElement>[]>([] as RefObject<HTMLDivElement>[]);
  const homeSectionRef = useRef(null);
  const projectSectionRef = useRef(null);
  const aboutSectionRef = useRef(null);
  const formSectionRef = useRef(null);

  useEffect(() => {
    if (!homeSectionRef || !projectSectionRef || !aboutSectionRef || !formSectionRef) return;
    setRefs([homeSectionRef, aboutSectionRef, projectSectionRef, formSectionRef]);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar refs={refs} />
        <HomeSection ref={homeSectionRef} />
        <AboutSection ref={aboutSectionRef} />
        <ProjectSection ref={projectSectionRef} />
        <ContactSection ref={formSectionRef} />
        <Footer />
      </main>
    </>
  );
}
