import Head from 'next/head';
import React, { RefObject, useEffect, useRef, useState } from 'react';
import { HomeContent } from '../components/HomeContent';
import Navbar from '../components/Navbar';

export default function Home() {
  const [refs, setRefs] = useState<RefObject<HTMLDivElement>[]>([] as RefObject<HTMLDivElement>[]);
  const mainContentRef = useRef(null);
  const aboutRef = useRef(null);

  useEffect(() => {
    if (!mainContentRef.current || !aboutRef.current) return;
    setRefs([mainContentRef, aboutRef]);
  }, [mainContentRef]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar refs={refs} />
        <HomeContent ref={mainContentRef} />
        <HomeContent ref={aboutRef} />
      </main>
    </>
  );
}
